name: stage
services:
  docker-daemon:
    image: docker:dind
    container_name: ${COMPOSE_PROJECT_NAME}-docker-daemon
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2378:2376"
    networks:
      jenkins:
        aliases:
          - docker
    command: --storage-driver overlay2

  jenkins-controller:
    image: jenkins-controller
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}-jenkins-controller
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8082:8080"
      - "50002:50000"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data: