pipeline {
    agent any

    stages {
        stage('w/o docker') {
            steps {
                sh '''
                    echo "Without docker"
                    ls -la
                    pwd
                    touch without-docker.txt
                '''
            }
        }

        stage('w/ docker') {
            agent {
                docker {
                    image 'node:18-alpine'
                }
            }
            steps {
                sh '''
                    echo "using docker agent"
                    ls -la
                    pwd
                    touch with-docker.txt
                '''
            }
        }
    }
}
